export const DATA = [
    {
        id: 1,
        title: "Circle of Friends",
        author: "Maeve Binchy",
        summary: "Circle of Friends is the story of three friends who become entangled in an odd love triangle on their journey to adulthood. Benny and Eve, close friends from the Irish village of Knockglen, go to study in Dublin and quickly befriend the attractive and ambitious Nan. However, the exciting student life brings them not only happiness but also sorrow. With her great ability to portray human emotions, Maeve Binchy brings together happiness and sorrow, warmth and humor in this captivating novel. Circle of Friends was first published in 1991 and has become a favorite among many Maeve Binchy fans. The book is now in its seventeenth printing. In 1995, it was successfully adapted into a film starring Minnie Driver and Chris O'Donnell.",
        image: "http://s.s-bol.com/imgbase0/imagebase/large/FC/5/3/6/6/1001004011806635.jpg",
        price: ["EUR", "10.00"],
        year: "1991"
    },
    {
        id: 2,
        title: 'Deception point',
        author: 'Dan Brown',
        summary:
            'When a new NASA satellite detects evidence of an astonishingly rare object buried deep in the Arctic ice, the floundering space agency proclaims a much-needed victory.. a victory that has profound implications for U.S. space policy and the impending presidential election. With the Oval Office in the balance, the President dispatches White House Intelligence analyst Rachel Sexton to the Arctic to verify the authenticity of the find. Accompanied by a team of experts, including the charismatic academic Michael Tolland, Rachel uncovers the unthinkable - evidence of scientific trickery - a bold deception that threatens to plunge the world into controversy..',
        image:
            'http://s.s-bol.com/imgbase0/imagebase/large/FC/8/8/9/8/1001004006878988.jpg',
        price: ['EUR', '9.99'],
        year: '2001',
    },
    {
        id: 3,
        title: 'Magic Staff',
        author: 'Terry Brooks',
        summary: "Five centuries ago, the world was laid to waste by a disastrous demon war. The survivors have found refuge in a valley protected by magic, but now a ruthless army is poised to invade the valley. The only hope of salvation for the survivors was Sider Ament, but he is no longer alive. Sider was the bearer of the last remaining black staff, a powerful talisman passed down for centuries by the Knights of the Word and crucial for maintaining the balance of magic in the world. To save the world from destruction, the magic of the staff must be preserved. Panterra Qu, a young Trackers who inherits the staff after Sider's death, struggles greatly to wield its power. Everything is at stake, for everyone will pay a high price if the war between the Word and the Void threatens to slide into darkness.",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/2/2/5/2/9200000002212522.jpg',
        price: ['EUR', '17.50'],
        year: '1857'
    },
    {
        id: 4,
        title: 'Bloodfire Quest',
        author: 'Terry Brooks',
        summary:
            'The adventure that started in Wards of Faerie takes a thrilling new turn, in the second novel of New York Times bestselling author Terry Brooks’s brand-new trilogy—The Dark Legacy of Shannara! The quest for the long-lost Elfstones has drawn the leader of the Druid order and her followers into the hellish dimension known as the Forbidding, where the most dangerous creatures banished from the Four Lands are imprisoned. Now the hunt for the powerful talismans that can save their world has become a series of great challenges: a desperate search for kidnapped comrades, a relentless battle against unspeakable predators, and a grim race to escape the Forbidding alive. But though freedom is closer than they know, it may come at a terrifying price. Back in the village of Arborlon, the mystical, sentient tree that maintains the barrier between the Four Lands and the Forbidding is dying. And with each passing day, as the breach between the two worlds grows larger, the threat of the evil eager to spill forth and wreak havoc grows more dire. The only hope lies with a young Druid, faced with a staggering choice: cling to the life she cherishes or combat an army of darkness by making the ultimate sacrifice.',
        image:
            'http://s.s-bol.com/imgbase0/imagebase/large/FC/7/0/0/7/9200000009027007.jpg',
        price: ['EUR', '24.50'],
        year: '2013',
    },
    {
        id: 5,
        title: 'A Week in Winter',
        author: 'Maeve Binchy',
        summary:
            "Stoneybridge is full of holiday-makers in summer, its beaches are full of buckets and spades and sandcastles; but in winter it's cold and wild. Few choose to walk along the fine sands, the big round pebbles and the exposed rocky promontories that make up the wind-swept Atlantic coastline. Those who do can't help but see Stone House, the big house on the cliff; once falling into disrepair it is now a beautiful hotel specialising in winter holidays. Its big, warm kitchen, its open log-fires and its elegant bedrooms provide a welcome few can resist, whatever their reasons for coming. Henry and Nicola are burdened with a terrible secret, while cheerful nurse Winnie finds herself on the holiday from hell. John has arrived on an impulse after he missed a flight at Shannon; eccentric Freda claims to be a psychic - and a part-time hairdresser. Then there's Nora, a silent watchful older woman who seems ready to disapprove at any moment.. A Week in Winter is full of Maeve's trademark warmth, humour and characters you want to spend time with.",
        image:
            'http://s.s-bol.com/imgbase0/imagebase/large/FC/6/2/8/0/9200000008070826.jpg',
        price: ['EUR', '11.99'],
        year: '2012',
    },
    {
        id: 6,
        title: 'Blue Curacao',
        author: 'Linda van Rijn',
        summary: "When her newlywed husband disappears without a trace during their honeymoon, Hannah is faced with a mystery. How well does she actually know the people she has always... Hannah and Koen's romantic honeymoon to Curaçao is rudely interrupted when Koen disappears without a trace while snorkeling. Hannah is consumed with fear. The local police aren't moving as quickly as Hannah would like, so she takes matters into her own hands and starts investigating. This search reveals unpleasant truths. As Hannah begins to fear for her own life, she is confronted with the question of whether she really knows Koen as well as she thinks.",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/0/9/4/2/9200000010732490.jpg',
        price: ['EUR', '48.99'],
        year: '2012'
    },
    {
        id: 7,
        title: 'Safe Haven',
        author: 'Nicholas Sparks',
        summary:
            'Love hurts. There is nothing as painful as heartbreak. But in order to learn to love again you must learn to trust again. When a mysterious young woman named Katie appears in the small town of Southport, her sudden arrival raises questions about her past. Beautiful yet unassuming, Katie is determined to avoid forming personal ties until a series of events draws her into two reluctant relationships. Despite her reservations, Katie slowly begins to let down her guard, putting down roots in the close-knit community. But even as Katie starts to fall in love, she struggles with the dark secret that still haunts her ...',
        image:
            'http://s.s-bol.com/imgbase0/imagebase/large/FC/0/5/2/3/9200000010683250.jpg',
        price: ['EUR', '33.80'],
        year: '2010',
    },
    {
        id: 8,
        title: 'The World According to Garp',
        author: 'John Irving',
        summary: "The World According to Garp is a rare comical, original, but also shocking novel that made John Irving famous overnight. Since its publication in 1978, millions of readers have enjoyed the eccentric, non-conformist Jenny, her son T.S. Garp, and the fanatics, innocent children, transsexuals, prostitutes, wrestlers, and the many other characters that populate Garp's world. The World According to Garp is a classic, a masterful tragicomedy that will leave a deep impression on the reader.",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/6/3/6/7/1001004005997636.jpg',
        price: ['EUR', '19.90'],
        year: '1978',
    },
    {
        id: 9,
        title: 'Winter Chalet',
        author: 'Linda van Rijn',
        summary: "Four friends enjoy a skiing holiday in Kirchberg. The murder of one of them puzzles everyone... During a cozy skiing holiday in the Austrian Kirchberg, friends Isa, Chantal, Karen, and Annemieke finally have the opportunity to spend time together. Karen, Chantal, and Isa arrive on Saturday, while Annemieke joins later as she still has to work. The vacation of the three starts very pleasantly. The friends have the chance to catch up, something that often gets neglected in busy daily life, and the weather is beautiful for skiing, which they do with great pleasure. However, the cozy skiing holiday takes a tragic turn on the day Annemieke arrives. Upon arrival, she finds one of her friends dead. Inspector GŸnter Wolfsberg of the Kirchberg police starts an investigation. He interrogates all the friends and their partners and discovers that beneath the surface of happy relationships and intense friendship, there are hidden tensions. It seems that some people are very eager to shift the blame...",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/6/6/6/7/9200000002547666.jpg',
        price: ['EUR', '15.00'],
        year: '2020',
    },
    {
        id: 10,
        title: 'The Kite Runner',
        author: 'Khaled Hosseini',
        summary: "Amir and Hassan are fed by the same nurse and grow up together in the capital of Afghanistan. As a sign of their bond, Amir carves their names into a pomegranate tree: 'Amir and Hassan, the sultans of Kabul.' But they are only sultans in their imagination because Amir belongs to the privileged population group while Hassan and his father are poor Hazaras, in service to Amir's father. During the annual kite-fighting tournament in Kabul, Amir is the kite flyer, the one who holds the kite's string. Hassan is his helper, the kite runner. 'For you, a thousand times over!' Hassan shouts before he runs off to catch the falling kite. That boundless loyalty is not mutual. When something terrible happens to Hassan, he betrays his loyal companion. After the Russian invasion, Amir and his father flee to the United States. Amir builds a new life there, but he fails to forget Hassan. The discovery of a shocking family secret eventually leads him back to Afghanistan, now occupied by the Taliban. There, Amir is confronted with ghosts from his past. His intention to redeem his old debt to Hassan drags him involuntarily into a horrifying adventure. The Kite Runner has been adapted into a film by Marc Foster.",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/6/3/5/1/1001004010981536.jpg',
        price: ['EUR', '6.99'],
        year: '2003',
    },
    {
        id: 11,
        title: 'Deception Point',
        author: 'Dan Brown',
        summary: "He's back... A scientific revolution, a stunning deception, a lightning-fast thriller! Beneath the polar ice, lies something that could change the world forever... A NASA satellite makes a sensational discovery at the North Pole. This is a boon for the space agency, which has long been under fire. It's also good news for President Zach Herney: a second term in the White House seems within reach. The president asks Rachel Sexton, an analyst at the intelligence agency NRO, to verify the authenticity of the find. She hastily travels to the Arctic to check the work of a team of scientists, including the charismatic oceanographer Michael Tolland. But after Rachel's arrival, the case takes an unexpected turn. The 'evidence' seems less solid than originally thought. Before the president can be warned, a nightmare begins on the polar ice. A special unit is tasked with its mission: to prevent the truth from coming out at all costs... After 'Digital Fortress,' but before 'The Da Vinci Code,' Dan Brown wrote this 'sophisticated blend of action and intrigue' (Publishers Weekly). Once again, he focuses on a shadowy secret service. This National Reconnaissance Office is closely intertwined with the famous space agency NASA. Dan Brown is the bestselling author of the moment. 'The Da Vinci Code' topped the charts for months, and 'Angels & Demons' and 'Deception Point' also effortlessly found their way to consumers. This year, too, will be dominated by Dan Brown, as in May 'The Da Vinci Code,' the major blockbuster of 2006, will premiere worldwide.",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/5/0/5/5/1001004006225505.jpg',
        price: ['EUR', '14.95'],
        year: '2001',
    },
    {
        id: 12,
        title: 'Can You Keep a Secret?',
        author: 'Sophie Kinsella',
        summary: "Emma, like all young women in the world, has a few secrets. From her parents, her boyfriend, her colleagues. Like she lost her virginity in the guest room while her parents were watching a movie, and she thinks her boyfriend Connor looks a bit like Ken. Barbie and Ken's. She gives her annoying colleague's plant orange juice - almost daily - and her thong hurts. Emma is always nervous when she has to fly. That's why she tells all her secrets to a nice stranger sitting next to her on the plane. At least, Emma thinks he's a stranger. Because when she comes to work the next day... Sophie Kinsella is a bestselling author and journalist. She lives in London. She doesn't have many big secrets, except that she's not fond of flying.",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/8/3/1/6/1001004002056138.jpg',
        price: ['EUR', '10.00'],
        year: '2003',
    },
    {
        id: 13,
        title: 'In One Person',
        author: 'John Irving',
        summary: "In One Person is a compelling novel about desire, secrecy, and sexual identity. A book about love in all its forms and a passionate plea for sexual diversity. Billy, the bisexual protagonist, tells the tragicomic story (spanning more than five decades) of his life as a 'sexual suspect,' a term John Irving first used in his immortal novel The World According to Garp. This is John Irving's most political novel since The Cider House Rules and A Prayer for Owen Meany, and a poignant tribute to Billy's friends and lovers—a colorful array of characters that readers won't soon forget. It's an unforgettable portrait of the lonely, bisexual man who has vowed to be 'truly important.'",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/0/7/8/7/9200000000037870.jpg',
        price: ['EUR', '19.90'],
        year: '2012',
    },
    {
        id: 14,
        title: 'The lucky one',
        author: 'Nicholas Sparks',
        summary:
            'Do you believe in lucky charms? While in Iraq, U.S. Marine Logan Thibault finds a photo, half-buried in the dirt, of a woman. He carries it in his pocket, and from then on his luck begins to change. Back home, Logan is haunted by thoughts of war. Over time, he becomes convinced that the woman in the photo holds the key to his destiny. So he finds the vulnerable and loving Beth and a passionate romance begins. But Logan battles with the one secret he has kept from Beth: how he found her in the first place. And it is a secret that could utterly destroy everything they love ...',
        image:
            'http://s.s-bol.com/imgbase0/imagebase/large/FC/7/0/3/7/1001004011797307.jpg',
        price: ['EUR', '9.80'],
        year: '2004',
    },
    {
        id: 15,
        title: 'Best of me',
        author: 'Nicholas Sparks',
        summary:
            'The new epic love story by the bestselling author of The Last Song and The Notebook. They were teenage sweethearts from opposite sides of the tracks - with a passion that would change their lives for ever. But life would force them apart. Years later, the lines they had drawn between past and present are about to slip.. Called back to their hometown for the funeral of the mentor who once gave them shelter when they needed it most, they are faced with each other once again and forced to confront the paths they chose. Can true love ever rewrite the past?',
        image:
            'http://s.s-bol.com/imgbase0/imagebase/large/FC/4/6/2/8/9200000001208264.jpg',
        price: ['EUR', '13.80'],
        year: '2004',
    },
    {
        id: 16,
        title: 'Hotel by the Sea',
        author: 'Maeve Binchy',
        summary: "In the summer, the seaside town of Stoneybridge is bustling with activity. Holidaymakers stroll around everywhere, and the beaches are scattered with buckets, spades, and sandcastles. But in the winter, almost no one ventures to the beautiful beaches and rugged cliffs that make up the rugged west coast of Ireland. The few who do visit the coast cannot miss the Stone House hotel. There, every guest can count on a warm welcome from owner Chicky Starr, regardless of the reason for their visit. Henry and Nicola carry a terrible secret with them, cheerful nurse Winnie sees her vacation plans ruined, and John shows up unexpectedly after missing his flight. The eccentric Freda is a psychic—and part-time hairdresser. And then there's Nora, a silent elderly lady who seems to have her own opinions about everything. Hotel by the Sea is a heartwarming novel with all the ingredients of a classic Maeve Binchy: warmth, humor, and delightful characters you'll love spending time with!",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/7/2/1/0/9200000009850127.jpg',
        price: ['EUR', '14.99'],
        year: '2004',
    },
    {
        id: 17,
        title: 'Inferno',
        author: 'Dan Brown',
        summary: "Inferno, the fourth Robert Langdon thriller, takes place in Italy. 'Although I read Dante's Inferno during my studies, it wasn't until recently, when I was researching in Florence, that I truly appreciated the influence of Dante's work on the modern era,' Brown explains. 'I look forward to taking readers on a journey to this mysterious world in my new book, a landscape full of codes, symbols, and secret passages.'",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/8/9/9/9/9200000010839998.jpg',
        price: ['EUR', '17.49'],
        year: '2004',
    },
    {
        id: 18,
        title: 'The Hour Game',
        author: 'David Baldacci',
        summary: "This is the poignant story of twelve-year-old Louisa Mae Cardinal, who lives in New York with her shy brother Oz. It is 1940 and they are not well-off because their father, a writer, doesn't earn much. But Lou doesn't care much about that because she adores her father and loves his stories. But then, in one terrible moment, Lou's life changes forever. A car accident ends their father's life, forcing her and Oz to move to distant Virginia. There, in the isolation of the desolate mountains, they come to live with their eccentric great-grandmother, Lou's namesake. Faced with new responsibilities, Lou is forced to grow up quickly. There, on her great-grandmother's simple farm, on the land her father loved so much and wrote about repeatedly, she discovers who she really is and what she can mean to this world. And when a devastating tragedy strikes their new home, she can face the ensuing battle; a battle for justice and survival fought in a crowded courtroom in Virginia...",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/2/6/2/1/1001004005971262.jpg',
        price: ['EUR', '5.00'],
        year: '2004',
    },
    {
        id: 19,
        title: 'The Hit',
        author: 'David Baldacci',
        summary:
            'The trap is set. Failure is not an option. When government hit man Will Robie is given his next target he knows he’s about to embark on his toughest mission yet. He is tasked with killing one of their own, following evidence to suggest that fellow assassin Jessica Reel has been turned. She’s leaving a trail of death in her wake including her handler. The trap is set. To send a killer to catch a killer. But what happens when you can’t trust those who have access to the nation’s most secret intelligence?',
        image:
            'http://s.s-bol.com/imgbase0/imagebase/large/FC/6/5/2/3/9200000009123256.jpg',
        price: ['EUR', '21.99'],
        year: '2004',
    },
    {
        id: 20,
        title: 'The Tennis Party',
        author: 'Sophie Kinsella',
        summary: "The tennis weekend is Patrick's idea. His new country house, bought with the bonuses from his job as an investment advisor, is the perfect location. Patrick's wife Caroline doesn't yet know the real reason for the party. She's happy to see her old neighbors Stephen and Annie again, but she's less thrilled about the boastful Charles and his spoiled wife Cressida. And the last couple, Don and Valerie, both fiercely competitive, are simply unbearable. As the four couples settle in on the sunny terrace, it seems predetermined who the winners and losers are in life. But when the first ball is hit over the net, it marks the beginning of two days of flirting, tantrums, explosive arguments, and shocking revelations. With the arrival of an uninvited guest, it becomes clear that this weekend has nothing to do with tennis at all. Long before she became famous with her Shopaholic! series, Sophie Kinsella wrote seven novels under her own name, Madeleine Wickham. The Tennis Party, her very first book, was published when she was only twenty-four and has therefore always remained very special to her. This was followed by, among others, The Swimming Pool Party and Asking Price. Her work has been translated into more than thirty languages. The author lives with her husband and children in London. 'A sharp novel with keen observations. Light but deadly.' Mail on Sunday",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/3/7/6/4/9200000009984673.jpg',
        price: ['EUR', '18.50'],
        year: '2004',
    },
    {
        id: 21,
        title: 'In One Person',
        author: 'John Irving',
        summary: "A compelling novel of desire, secrecy, and sexual identity, In One Person is a story of unfulfilled love—tormented, funny, and affecting—and an impassioned embrace of our sexual differences. Billy, the bisexual narrator and main character of In One Person, tells the tragicomic story (lasting more than half a century) of his life as a “sexual suspect,” a phrase first used by John Irving in 1978 in his landmark novel of “terminal cases,” The World According to Garp. His most political novel since The Cider House Rules and A Prayer for Owen Meany, John Irving’s In One Person is a poignant tribute to Billy’s friends and lovers—a theatrical cast of characters who defy category and convention. Not least, In One Person is an intimate and unforgettable portrait of the solitariness of a bisexual man who is dedicated to making himself 'worthwhile.'",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/3/4/5/9/9200000009409543.jpg',
        price: ['EUR', '25.00'],
        year: '2004',
    },
    {
        id: 22,
        title: 'The Attack',
        author: 'David Baldacci',
        summary: "Will Robie is one of the best in his field, an assassin who never hesitates and always eliminates his target. He is the man the American government turns to when it comes to killing its greatest enemies, the monsters responsible for countless innocent victims. And no one is as good as Robie. No one, except Jessica Reel... Like Robie, Reel is highly experienced, extremely professional, and deadly accurate. But Reel has turned against her employer and is targeting her former colleagues within their agency. Now that one of their own needs to be stopped, Robie is called upon once again. His mission: capture or kill Reel. But when Robie begins the hunt for Reel, he quickly discovers that she may have valid reasons for her betrayal. The attacks on the agency are related to a much greater danger. A danger that will shake Washington D.C., the United States, and the rest of the world to its core...",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/4/8/2/7/9200000010047284.jpg',
        price: ['EUR', '19.99'],
        year: '2004',
    },
    {
        id: 23,
        title: 'Can You Keep a Secret?',
        author: 'Sophie Kinsella',
        summary: "Poppy Wyatt has lost her engagement ring! An antique, passed down through three generations of Magnus's family, her fiancé. The wedding is in ten days! And while she's outside on the phone with her friends, her mobile phone is suddenly snatched from her hands. Just great! Now the crisis is complete. What is she going to do without her phone? Completely hyped, Poppy thinks she's hallucinating when she sees a smartphone lying in a trash can. Jackpot! But it doesn't take long for the owner, the grumpy businessman Sam Roxton, to show up. And Sam is 'not amused' when Poppy coldly refuses to give him her treasure.",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/3/0/9/4/9200000009984903.jpg',
        price: ['EUR', '10.00'],
        year: '2004',
    },
    {
        id: 24,
        title: "Jarka Ruus",
        author: "Terry Brooks",
        summary: "Twenty years have passed since Grianne Ohmsford gave up her life as the dreaded Ilse Witch, was freed by the magic of the Sword of Shannara, and the destruction of her mentor, the Morgawr. Suddenly, when Grianne disappears, her young servant Tagwen is forced to take up the challenge and rescue her from her enemies, along with Grianne's young nephew Pen Ohmsford and the powerful elf Ahren Elessedil.",
        image: "http://s.s-bol.com/imgbase0/imagebase/large/FC/7/8/9/9/1001004011269987.jpg",
        price: ["EUR", "18.95"],
        year: "2004"
    },
    {
        id: 25,
        title: 'Last Minute',
        author: 'Linda van Rijn',
        summary: "On the last-minute holiday in Hurghada, Susan runs into her ex-boyfriend. She would rather never have seen him again... Susan Waterberg and her husband Hugo have been married and happy in Almere for five years. Susan doesn't want to let this milestone pass unnoticed. She arranges for her in-laws to babysit their three-year-old son Stijn and books a last-minute holiday to Hurghada. For Hugo, the trip is a big surprise, especially since he only got his PADI (diving certificate) a year ago. Now he can finally go diving for real. Although saying goodbye to little Stijn is hard for both of them, they are looking forward to a carefree beach holiday. When they check in at the diving school, Susan gets the fright of her life. The diving instructor is an old acquaintance and confronts her with a past she has always kept from Hugo. The carefree beach holiday Susan had in mind turns into a web of lies and blackmail. To keep her family together, she will have to finally settle her past.",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/2/5/6/7/1001004011817652.jpg',
        price: ['EUR', '4.99'],
        year: '2004',
    },
    {
        id: 26,
        title: 'A Thousand Splendid Suns',
        author: 'Khaled Hosseini',
        summary: "The uneducated Mariam is fifteen when she is married off to the thirty-year-old shoemaker Rasheed in Kabul. Years later, she must tolerate the beautiful and clever Laila by her side, who was rescued from the rubble by Rasheed after a rocket attack. Rasheed takes Laila into his home in the hope that she will give him the son Mariam cannot. Initially, suspicion and jealousy dominate between the two women, but Rasheed's tyrannical behavior gradually leads to a deep friendship. Together, Mariam and Laila do everything they can to survive in the endless war in Afghanistan, which also rages inside their home. After the overwhelming success of The Kite Runner, Khaled Hosseini once again surprises his readers with a breathtaking story",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/7/3/5/1/1001004010981537.jpg',
        price: ['EUR', '16.99'],
        year: '2004',
    },
    {
        id: 27,
        title: 'And the Mountains Echoed',
        author: 'Khaled Hosseini',
        summary: "And the Mountains Echoed is a deeply moving story about how we love, how we take care of one another and how the choices we make resonate through generations. With profound wisdom, depth, insight and compassion 'and moving from Kabul, to Paris, to San Francisco, to the Greek island of Tinos' Hosseini writes about the bonds that define us and shape our lives, the ways that we help our loved ones in need and how we are often surprised by the people closest to us. Six years in the writing, Khaled Hosseini says of his new book: 'My earlier novels were, at heart, tales of fatherhood and motherhood. My new novel is a multi-generational family story as well, this time revolving around brothers and sisters, and the ways in which they love, wound, betray, honour and sacrifice for each other.'",
        image: 'http://s.s-bol.com/imgbase0/imagebase/large/FC/0/6/0/3/9200000010223060.jpg',
        price: ['EUR', '8.99'],
        year: '2004',
    },
]